version: '3.8'
services:
  database:
    container_name: WxI98w-chum-postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: api
    ports:
      - '5442:5432'
  pgadmin:
    container_name: WxI98w-chum-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5052:80'
  mail:
    container_name: WxI98w-chum-mail
    image: axllent/mailpit
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 8022:8025
      - 1022:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  redis:
    container_name: WxI98w-chum-redis
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=root
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
      - '6372:6379'
